(ns glam.client.ui.material-ui-icon
  "Autogenerated. Go to https://mui.com/material-ui/material-icons/ and select the parent div in devtools

  Then:

  let pascalNames = Array.from($0.childNodes).map(x => x.innerText)
  console.log(pascalNames.map(x => `            [\"@mui/icons-material/${x}\" :default ${x}]`).join(\"\\n\"))
  let pascal2kebab = (s) => s.split('').map((c, i) => c === c.toUpperCase() && i > 0 ? '-' + c.toLowerCase() : c.toLowerCase()).join('')
  console.log(pascalNames.map(n => `(def ${pascal2kebab(n)} (interop/react-factory ${n}))`).join('\\n'))
  "
  (:refer-clojure :exclude [comment compare filter list loop map print remove repeat shuffle sort update])
  (:require [com.fulcrologic.fulcro.algorithms.react-interop :as interop]
            ["@mui/icons-material/Abc" :default Abc]
            ["@mui/icons-material/Add" :default Add]
            ["@mui/icons-material/ArrowDownward" :default ArrowDownward]
            ["@mui/icons-material/ArrowUpward" :default ArrowUpward]
            ["@mui/icons-material/Cancel" :default Cancel]
            ["@mui/icons-material/CloudDownload" :default CloudDownload]
            ["@mui/icons-material/Create" :default Create]
            ["@mui/icons-material/Delete" :default Delete]
            ["@mui/icons-material/DescriptionOutlined" :default DescriptionOutlined]
            ["@mui/icons-material/ExpandMore" :default ExpandMore]
            ["@mui/icons-material/Gavel" :default Gavel]
            ["@mui/icons-material/Home" :default Home]
            ["@mui/icons-material/HelpOutlineOutlined" :default HelpOutlineOutlined]
            ["@mui/icons-material/Menu" :default Menu]
            ["@mui/icons-material/MoreHoriz" :default MoreHoriz]
            ["@mui/icons-material/NavigateNext" :default NavigateNext]
            ["@mui/icons-material/Restore" :default Restore]
            ["@mui/icons-material/Save" :default Save]
            ["@mui/icons-material/Settings" :default Settings]
            ["@mui/icons-material/SettingsEthernet" :default SettingsEthernet]
            ["@mui/icons-material/SupervisorAccount" :default SupervisorAccount]
            ["@mui/icons-material/SupervisedUserCircleSharp" :default SupervisedUserCircleSharp]
            ["@mui/icons-material/WorkOutlineTwoTone" :default WorkOutlineTwoTone]
            ))

(def abc (interop/react-factory Abc))
(def add (interop/react-factory Add))
(def arrow-downward (interop/react-factory ArrowDownward))
(def arrow-upward (interop/react-factory ArrowUpward))
(def cancel (interop/react-factory Cancel))
(def cloud-download (interop/react-factory CloudDownload))
(def create (interop/react-factory Create))
(def delete (interop/react-factory Delete))
(def description-outlined (interop/react-factory DescriptionOutlined))
(def expand-more (interop/react-factory ExpandMore))
(def gavel (interop/react-factory Gavel))
(def home (interop/react-factory Home))
(def help-outline-outlined (interop/react-factory HelpOutlineOutlined))
(def menu (interop/react-factory Menu))
(def more-horiz (interop/react-factory MoreHoriz))
(def navigate-next (interop/react-factory NavigateNext))
(def restore (interop/react-factory Restore))
(def save (interop/react-factory Save))
(def settings (interop/react-factory Settings))
(def settings-ethernet (interop/react-factory SettingsEthernet))
(def supervisor-account (interop/react-factory SupervisorAccount))
(def supervised-user-circle-sharp (interop/react-factory SupervisedUserCircleSharp))
(def work-outline-two-tone (interop/react-factory WorkOutlineTwoTone))

