= Glam Manual
:author: Luke Gessler
:lang: en
:encoding: UTF-8
:doctype: book
:toc: left
:toclevels: 3
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: img/src
:imagesoutdir: img/out
:favicon: favicon.ico
:hide-uri-scheme: 1

= Introduction

Glam is an app for linguistic annotation.
While Glam is usable for many different kinds of annotation projects, it was originally developed to serve https://en.wikipedia.org/wiki/Language_documentation[**language documentation**] projects, and in pursuit of that, aims to achieve the following core goals:

- **Modular Data Schema**: users should be able to record however much data and whatever kind of data they desire.
Annotating anything from good old-fashioned https://en.wikipedia.org/wiki/Interlinear_gloss[interlinear glossed text] to more complicated schemas like https://universaldependencies.org/format.html[Universal Dependencies] should be possible and easy.
- **Durability**: data should never be lost--all past states of the database should be recorded, and the present state of the database should be a single source of truth.
- **Seamless collaboration**: working with others should be frictionless--users should be able to share data without thinking about it, changes made to data should be viewable by everyone in real time, and new users should be able to be onboarded quickly.
- **NLP model integration**: it should be easy to configure cutting-edge NLP models to provide best-effort annotations to be corrected by humans, and have them train themselves incrementally as new gold annotations become available.
- **Hackable UIs**: Programmers who want to provide new UIs for different kinds of annotation (e.g. entity recognition, syntax, and coreference) should be able to do so just by writing JavaScript using the Glam API, with no backend changes required.

= Core Concepts

= Workflows

= Developer's Guide

CAUTION: This section is intended only for people who want to extend Glam. You do not need to read this section in order to use Glam.